export const audioMap = {
  "intro":        new URL("../audio/Tutorial.wav",      import.meta.url).href,
  "aries":        new URL("../audio/Aries.wav",         import.meta.url).href,
  "taurus":       new URL("../audio/Taurus.wav",        import.meta.url).href,
  "gemini":       new URL("../audio/Gemini.wav",        import.meta.url).href,
  "cancer":       new URL("../audio/Cancer.wav",        import.meta.url).href,
  "leo":          new URL("../audio/Leo.wav",           import.meta.url).href,
  "virgo":        new URL("../audio/Virgo.wav",         import.meta.url).href,
  "libra":        new URL("../audio/Libra.wav",         import.meta.url).href,
  "scorpius":     new URL("../audio/Scorpius.wav",      import.meta.url).href,
  "sagittarius":  new URL("../audio/Sagittarius.wav",   import.meta.url).href,
  "capricornus":  new URL("../audio/Capricornus.wav",   import.meta.url).href,
  "aquarius":     new URL("../audio/Aquarius.wav",      import.meta.url).href,
  "pisces":       new URL("../audio/Pisces.wav",        import.meta.url).href,
  "orion":        new URL("../audio/Orion.wav",         import.meta.url).href,
  "canis-minor":  new URL("../audio/Canis Minor.wav",   import.meta.url).href,
  "bootes":       new URL("../audio/Bootes.wav",        import.meta.url).href,
  "auriga":       new URL("../audio/Auriga.wav",        import.meta.url).href,
  "cassiopeia":   new URL("../audio/Cassiopeia.wav",    import.meta.url).href,
  "ursa-minor":   new URL("../audio/Ursa Minor.wav",    import.meta.url).href,
  "ursa-major":   new URL("../audio/Ursa Major.wav",    import.meta.url).href,
  "lyra":         new URL("../audio/Lyra.wav",          import.meta.url).href,
  "aquila":       new URL("../audio/Aquila.wav",        import.meta.url).href,
  "cygnus":       new URL("../audio/Cygnus.wav",        import.meta.url).href,
  "canis-major":  new URL("../audio/Canis Major.wav",   import.meta.url).href,
  "phoenix":      new URL("../audio/Phoenix.wav",       import.meta.url).href,
};
